apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: client-deployment
  namespace: default
spec: 
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: client-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics: 
  - type: Pods
    pods:
      metricName: requests_per_second
      targetAverageValue: 40
  - type: Pods
    pods:
      metricName: response_latency_ms_99th
      targetAverageValue: 500
 