apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: position-tracker
  namespace: default
spec: 
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: position-tracker
  minReplicas: 1
  maxReplicas: 10
  metrics: 
  - type: Pods
    pods:
      metricName: requests_per_second
      targetAverageValue: 40